engines:
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      import/no-unresolved:
        enabled: false
checks:
  method-lines:
    config:
      threshold: 100
  similar-code:
    enabled: false
exclude_patterns:
  - "__tests__"
  - "lib/plugins/source/contingentSource.js"
