sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '8'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run semantic-release
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: 29ce6bf53481ef6a27f450828e5fda19131dea1c930dea0a234791a53b646468
