sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - yarn run lint
  - yarn test
after_success:

branches:
  except:
    - /^v\d+\.\d+\.\d+$/



sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: release
    # require the branch name to be one of the environment branches.
    if: branch = master AND fork = false AND type IN (push, api)

jobs:
  include:
    - stage: test
      node_js: 'lts/carbon'
      script:
        - yarn run lint
        - yarn test

    - stage: release
      node_js: 'lts/carbon'
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script:
        - yarn run coveralls
        - yarn semantic-release-github
        - yarn npm-publish-git-tag --access public