sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: deploy
    # require the branch name to be one of the environment branches.
    if: branch IN (master) AND fork = false AND type IN (push, api)

jobs:
  include:
    -
      stage: test
      node_js: 'lts/dubnium'
      script:
        - yarn run lint
        - yarn test
        - yarn coveralls
    - 
      stage: deploy
      if: branch = master
      # Semantic release will fail if it's not using node 8.
      node_js: 'lts/dubnium'
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release