sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

stages:
  - name: test
    # require the event type to not be a semantic release tag.
    if: NOT tag =~ ^v\d+\.\d+\.\d+$
  - name: release
    # require the branch name to be one of the environment branches.
    if: branch = master AND fork = false AND type IN (push, api)

jobs:
  include:
    - stage: test
      node_js: 'lts/carbon'
      script:
        - yarn run lint
        - yarn test
        - yarn run coveralls

    - stage: release
      node_js: 'lts/carbon'
      script:
        - yarn semantic-release-github
        - yarn npm-publish-git-tag --access public